### ISSUE TITLE
Revoke 3.3.1, it's a mistake

### ISSUE THREAD

**Issue by steida** [pburtchaell/redux-promise-middleware#100] opened 2016-07-11 00:25 UTC
- Never modify existing errors! You don't know which props are already set, JavaScript error can be subclassed fyi.
- The API is super inconsistent now. And you added a circular dependency.
- Use semantic versioning please, this was clearly a big breaking change. Don't lie and increment X from X.Y.Z. Thank you.

Anyway, thank you for your work. The open source is hard.

**Comment by steida** [comment] 2016-07-11 00:36
Use https://github.com/JsCommunity/make-error for custom redux-promise-middleware error with action and reason props.

**Comment by steida** [comment] 2016-07-11 00:44
Never ever mutate existing object. http://henrikeichenhardt.blogspot.cz/2013/06/why-shared-mutable-state-is-root-of-all.html

**Comment by steida** [comment] 2016-07-11 00:45
An inspiration https://github.com/este/este/blob/master/src/common/lib/validation/ValidationError.js

**Comment by steida** [comment] 2016-07-11 00:48
I hope this is constructive enough. Feel free to ask.

**Comment by pburtchaell** [comment] 2016-07-11 01:37
> Never modify existing errors!

Let's take a step back. In issue #70, we changed the middleware to reject with an instance of Error. This request is reasonable, but also problematic because constructing a new error renders `Error.prototype.stack` — as well as the other properties from the original error — useless. Thus, the goal of version 3.3.1 was to preserve the original error object while adding the properties from the middleware. See issue #93. 

This is the solution implemented version 3.3.1, as I am sure you are aware.

```js
const error = reason instanceof Error ? reason : new Error();
error.reason = reason;
error.action = rejectedAction;
throw error;
```

Yes, it is not ideal to mutate objects; I am aware. Personally, in order to resolve this issue, I’d like to revert the changes made as a result of #70. Another option would be to subclass the error, e.g., `class FooError extends Error`, but you would still end up mutating the original object to account for issue #93. What would you suggest?

> Use semantic versioning please, this was clearly a big breaking change. Don't lie and increment X from X.Y.Z. Thank you.

Unrelated, but important: you should reconsider how you engage with open source contributors. 

**First, issue #99 was entirely uncalled for and not constructive.** I get it: it is frustrating when code does not work as expected and it turns out to be someone's library. I'm sorry you had trouble with the versioning; frankly, I was not expecting this to break anything. However, it makes me bitter to be engaged with in this manner. I'm not paid to do open source work and I am here to help you. You should remember to be constructive and kind.

**Second, your engagement on issues suggests arrogance.** Your description/comments on issues are short/curt and do not include context. 

- "The API is super inconsistent now": Why is it inconsistent? 
- "And you added a circular dependency": What is the circular dependency? 
- You have mentioned several times this was a breaking change for you, but never mentioned what the breaking change is! What did you experience? Can you provide context? The issue template explicitly asks for “Expected Behavior” and “Actual Behavior.” This is important information.
- "JavaScript error can be subclassed": Do you think I don't know this? 
- Your comments on issue #77 are not constructive
-  From issue #99: "I just wonder what is so magic with simple stupid promise handling that every new release breaks my Este dev stack.": Really? 

**Third, I might suggest making a pull request if you have a solution in mind.** I would be happy to accept your contributions, especially as more people are using the project. I do not have a lot of time to resolve issues and review code. I work full-time and have other commitments.

**Fourth, remember issues are considered contributions.** How are your issues contributing to the project? You open issues, but don't propose any applicable solutions. In issue #70, I asked for an example to demonstrate the change you requested. You responded with “That's the only code I can provide you right now.” and a link. Today, you opened several issues, but I still don't know why version 3.3.1 is a mistake.

**Comment by pburtchaell** [comment] 2016-07-11 03:10
I am marking as invalid until I have more context around the expected and actual behavior.

**Comment by tomatau** [comment] 2016-07-11 06:51
@steida you can still use v2 of this middleware. It doesn't modify errors - they just pass through to both the consumer and the dispatch.

**Comment by steida** [comment] 2016-07-11 20:52
Sorry for being rude and thank you for the thoughtful answer.
The problem with recent change is, that it makes a circular dependency. Look:

```js
const error = reason instanceof Error ? reason : new Error();
error.reason = reason;
```

Now reason has a property reason, which has a property reason, which... brokes JSON.stringify, which is often used in redux-logger or redux storage. This is why mutation can be so tricky.

What I suggest is to always create a new Error. Maybe stack can be preserved. If not, then we have to change the current API to be more idiomatic promise-like. I mean _SUCCESS and _ERROR getting result or rejection object without any wrapper. Then to figure out how to pass original action, not sure how yet.

I will try something.

**Comment by tomatau** [comment] 2016-07-11 20:56
I feel it's the responsibility of the consumer to make sure their payload is a real error instance in the rejected case and we shouldn't be mutating or creating anything. Smaller API surface's always seem to work out better.

I don't really get the need for this object with a reason property... surely the reason is the payload already. If anyone needs to know the full "rejected action" then they can just use some logging middleware...

**Comment by steida** [comment] 2016-07-11 21:10
I think the reason for the reason (haha) is having an action so a handler can do something with it for an optimistic update I guess. Not needed in Este, still some people can leverage it. It allows reducer to know what caused the change. But it also gibberish an API with an additional level of the abstraction. I think it can be removed entirely in version 4.

**Comment by steida** [comment] 2016-07-11 21:38
Hmm, it seems we can use this to pass preserve stack.
But I would rather remove the whole wrapping. It's confusing I suppose.

```js
defineProperty(error, 'stack', {
  configurable: true,
  get: function getStack() {
    var stack = reason.stack;
    // Replace property with value for faster future accesses.
    defineProperty(this, 'stack', {
      value: stack
    });
    return stack;
  },
  set: function setStack (stack) {
    defineProperty(error, 'stack', {
      configurable: true,
      value: stack,
      writable: true
    })
  }
})
```

**Comment by tomatau** [comment] 2016-07-11 21:59
Anyone could wrap their catched payload before it dispatches in the action creator if they needed to optimistic update their reject flow... if that's even a thing? Surely the reducer just needs to rollback and maybe store some 'error' state from the rejection payload. Anyway it's still a pretty obscure use case to have baked into a middleware - especially as anyone can just create it themselves with a bit of composition.

**Comment by steida** [comment] 2016-07-11 22:19
MVP

```js
const promiseMiddleware = config => ({ dispatch }) => next => action => {
  const {
    suffixes = ['PENDING', 'FULFILLED', 'REJECTED']
  } = config || {};
  const [PENDING, FULFILLED, REJECTED] = suffixes;
  const { type, payload: promise } = action;
  const isPromise = promise && typeof promise.then === 'function';
  if (!isPromise) {
    return next(action);
  }
  next({ type: `${type}_${PENDING}`, payload: action });
  const handleFulfilled = value => {
    dispatch({ type: `${type}_${FULFILLED}`, payload: value });
    return result;
  };
  const handleRejected = error => {
    dispatch({ type: `${type}_${REJECTED}`, payload: error });
    throw error;
  };
  return promise.then(handleFulfilled, handleRejected);
}
```

**Comment by steida** [comment] 2016-07-11 23:12
I think this is what I need in the Este

```js
// Like redux-promise-middleware but without the noise.
const promiseMiddleware = ({ dispatch }) => next => action => {
  const { type, payload: promise } = action;
  const isPromise = promise && typeof promise.then === 'function';
  if (!isPromise) return next(action);
  const createAction = (suffix, payload) => ({
    type: `${type}_${suffix}`, meta: { action }, payload
  });
  next(createAction('START'));
  const handleFulfilled = value => {
    dispatch(createAction('SUCCESS', value));
    return value;
  };
  const handleRejected = error => {
    dispatch(createAction('ERROR', error));
    throw error;
  };
  return promise.then(handleFulfilled, handleRejected);
};
```

**Comment by pburtchaell** [comment] 2016-07-15 00:36
There is a related PR open to remove the circular reference for this:  #101. I explained in a comment there what my thoughts are for this. TL;DR: don't construct a new error and release v4.

As far as simplifying the rest of the code, I don't think it is productive. Yeah, it is easier to _explain_ with a MVP, but it is just that: an MVP. As this project has grown from the first release to now, we have received a number of feature requests. If there are ways to make the code cleaner while maintaining the present API, I am open to this; however, I don't want to depreciate any of the API.

**Comment by steida** [comment] 2016-07-15 00:42
What exactly is omitted in my suggested implementation?

**Comment by pburtchaell** [comment] 2016-07-15 00:48
> What exactly is omitted in my suggested implementation?

1. There is no config for custom type suffixes
2. There is no support for optimistic updates via the pending action 
3. Can only dispatch promises via `payload` and not `payload.promise` (current middleware supports both)

**Comment by steida** [comment] 2016-07-15 01:33
> There is no config for custom type suffixes
I'm pretty sure it's unnecessary abstraction, but you probably overlooked, that first example https://github.com/pburtchaell/redux-promise-middleware/issues/100#issuecomment-231883107 supports it.
```js
const {
  suffixes = ['PENDING', 'FULFILLED', 'REJECTED']
} = config || {};
const [PENDING, FULFILLED, REJECTED] = suffixes;
```

> There is no support for optimistic updates via the pending action
There is. Instead of misusing payload which really belongs to promise value only, the whole action is always passed into the meta, where it belongs. Again you probably overlooked it.
```js
const createAction = (suffix, payload) => ({
  type: `${type}_${suffix}`, meta: { action }, payload
});
```

> Can only dispatch via payload and not payload.promise (v3 supports both)
And what? Version 4 can simply API and version 4 means breaking change so there is no reason to support obsolete API.

Remember, the API developer should always provide only the one way to do stuff.

**Comment by steida** [comment] 2016-07-15 01:45
@tomatau WDYT?

**Comment by tomatau** [comment] 2016-07-15 08:10
I like v2 that I maintain, it's essentially what you're asking for but also lets you modify the meta on each action type which is an important use case for me when working with sockets.

**Comment by pburtchaell** [comment] 2016-08-05 22:32
So revisiting this after a busy month, @steida.

Your response to "There is no config for custom type suffixes"

> I'm pretty sure it's unnecessary abstraction.

It is a reasonable objection. This _was_ a requested feature in the early days of the middleware, but I have not used it myself. I'd consider removing it for a v4 release.

Your response to "There is no support for optimistic updates via the pending action":

> There is. Instead of misusing payload which really belongs to promise value only, the whole action is always passed into the meta, where it belongs. Again you probably overlooked it.

Yes, I noticed your example dispatches the optimistic update in the meta, however, I disagree with this design. The payload of the _pending_ action should not be a promise value. It can't be, since the promise is not settled yet. The pending action payload should be optimistic update. 

As we all know, Redux actions describe change(s) to state. The dispatched pending action describes an change to state which is not fulfilled or rejected; thus, it makes sense for the optimistic update will remain in the payload of such an action. It is a pending change to state.

Your response to: "Can only dispatch via payload and not payload.promise (v3 supports both)"

> And what? Version 4 can simplify API and version 4 means breaking change so there is no reason to support obsolete API. Remember, the API developer should always provide only the one way to do stuff. http://semver.org/

1. `payload.promise` is needed to support optimistic updates 
2. You could put the value of the optimistic update in the `meta` — however, I would prefer to keep the middleware agnostic and allow both. 
3. It is too prescriptive to require `payload`to  _always_ be a promise.

I don't find this issue is going in any particular direction, so I am closing. Further changes can be discussed in #103 and #101 is open to track the circular reference bug.

**Closed by pburtchaell** 2016-08-05 22:32 UTC
