### ISSUE TITLE
How to dispatch supplementary actions?

### ISSUE THREAD

**Issue by tesujimath** [pburtchaell/redux-promise-middleware#24] opened 2015-11-19 05:06 UTC
Prior to using redux-promise-middleware, I was using redux-thunk middleware for my asynchronous actions.  The promise based approach is a lot nicer.  However, I have lost the flexibility to dispatch actions at arbitrary points in action processing, and can't see how to mitigate that.

Specifically, I am dispatching a fetch to authenticate the user, and on success, I want to change the router path, using updatePath from redux-simple-router.  Here's my action creator code:
```
export function requestLogin(email, password) {
  return {
    type: REQUEST_LOGIN,
    payload: {
      promise: new Promise((resolve, reject) => {
        fetch(`${baseUrl}/api/v0/authenticate/password`, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: email,
            password: password
          })})
          .then(response => response.json())
          .then(json => {
            // want to updatePath for the route here:
            //dispatch(updatePath('/'));
            resolve(json);
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  };
}
```

Any suggestions on how to handle this?

**Comment by tomatau** [comment] 2015-11-19 09:37
If the thunk middleware is in your reducer chain before promiseMiddleware, you could perhaps still wrap the promise action inside a thunk to gain access to the dispatch method.

Alternatively you could grab the dispatch method directly from the store (require your store into the action file) and invoke it directly inside your then block.

**Comment by pburtchaell** [comment] 2015-11-19 17:32
I have also had this issue in an app that I am using promises with. 

What I had done to solve the problem was modify the middleware to handle `onFulfilled` and `onRejected` callbacks if an action included them.

Your actions would look like: 

```js
export function requestLogin(email, password) {
  return {
    type: REQUEST_LOGIN,
    payload: {
      promise: () => {
        // make a network request to login the person
      },
      onFulfilled: (response) => { 
        // do something when the promise is fulfilled
      },
      onRejected: (error) => {
        // do something when the promise is rejected
      },
    }
  };
}
```

I usually pass in the handlers as callbacks like so: 

```
export function requestLogin(email, password, onFulfilled, onRejected) {
  return {
    type: REQUEST_LOGIN,
    payload: {
      promise: () => {
        // make a network request to login the person
      },
      onFulfilled,
      onRejected
    }
  };
}
```

If you think this would work to solve your problem, I can add it to the middleware.

**Comment by tomatau** [comment] 2015-11-19 19:56
I think that this shouldn't be added to the middleware as other solutions can already solve this problem and it's nice to keep the API surface small without limiting anything:

This could be achieved with the thunk middleware without making many modifications to your original code:
```
export function requestLogin(email, password) {
  // using a thunk
  return (dispatch) => ({
    type: REQUEST_LOGIN,
    payload: {
      promise: new Promise((resolve, reject) => {
        fetch(`${baseUrl}/api/v0/authenticate/password`, {
          method: 'POST',
          body: JSON.stringify({
            email: email,
            password: password
          })
        }).then(response => response.json())
          .then(json => {
            dispatch(updatePath('/'));
            resolve(json);
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  });
}
```

**Comment by tesujimath** [comment] 2015-11-19 21:46
In principle I agree with @tomatau that combining simple APIs is preferable.

In practice, however, I can't get the combination of thunk and promise middleware to work yet.  When I use a thunk as suggested above, the promise actions don't get reduced.

To further complicate things, there are also weird interactions between the promise middleware and the logger, which mean that when inspecting log output in the Chrome developer tools, promise actions get re-dispatched.  (Perhaps the logger needs to be promise-aware, ugh.)  My middleware stack looks like this:

```
const createStoreWithMiddleware = applyMiddleware(
  thunk,
  promiseMiddleware(),
  logger
)(createStore);
```
It seems harmless to re-order the promise and thunk middleware, but putting the logger in different places seems to make quite a diffference.

It may well be that @pburtchaell has the best idea, of adding callbacks.  In this case, I think my preference would be for those callbacks to be passed a dispatch parameter from the middleware, to facilitate dispatching the other action.  But I'm still thinking this through.

I will continue to investigate, and come back with further thoughts.

**Comment by tesujimath** [comment] 2015-11-19 22:49
The problem turns out to be a bug (or at least, a misfeature) in redux-thunk.  I got the example of @tomatau working after fixing the thunk middleware.  As it stood, it didn't pass on the action to the next middleware in the stack.  So I changed it from this:
```
export default function thunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      action(dispatch, getState) :
      next(action);
}
```
to this:
```
function myThunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      next(action(dispatch, getState)) :
      next(action);
}
```
And now it all works nicely.  I will raise this as an issue for redux-thunk, and hopefully get it fixed there.

Thanks for the good input.  Looks like we don't need an enhancement to the promise middleware after all.

**Comment by pburtchaell** [comment] 2015-11-20 01:37
Ok great. Let's keep this open for now until the issue is resolved on redux-thunk.

**Comment by tomatau** [comment] 2015-11-20 09:25
I'm not sure if the thunk middleware needs to be changed actually -- I made some mistakes in the code I posted:

I'll modify my solution as I mad some mistakes
```js
export function requestLogin(email, password) {
  return (dispatch) => {
    dispatch({ // call dispatch with promise action
      type: REQUEST_LOGIN,
      payload: {
        promise: new Promise((resolve, reject) => {
          fetch(`${baseUrl}/api/v0/authenticate/password`, {
            method: 'POST',
            body: JSON.stringify({
              email: email,
              password: password
            })
          }).then(response => response.json())
            .then(json => {
              dispatch(updatePath('/'));
              resolve(json);
            })
            .catch(error => {
              reject(error);
            });
        })
      }
    });
  };
}
```

if you're using the latest release of redux-promise-middleware, you can use the thunk at the end:

```js
export function requestLogin(email, password) {
  return ({ // call dispatch with promise action
    type: REQUEST_LOGIN,
    payload: {
      promise: new Promise((resolve, reject) => {
        fetch(`${baseUrl}/api/v0/authenticate/password`, {
          method: 'POST',
          body: JSON.stringify({
            email: email,
            password: password
          })
        }).then(response => response.json())
          .then(json => {
            resolve((dispatch) => {
              dispatch(updatePath('/'));
              dispatch(json)
            });
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  });
}
```

**Comment by tesujimath** [comment] 2015-11-20 21:27
Aha!  I found a simple way to get it working with the original unmodified middleware.  The critical observation is that redux-thunk requires actions to be dispatched explicitly.  So by dispatching the top-level promise action explicitly, it all works.  Like this:
```
export function requestLogin(email, password) {
  return (dispatch) => dispatch({
    type: REQUEST_LOGIN,
    payload: {
      promise: new Promise((resolve, reject) => {
        fetch(`${baseUrl}/api/v0/authenticate/password`, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: email,
            password: password
          })})
          .then(response => response.json())
          .then(json => {
            dispatch(updatePath('/'));
            resolve(json);
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  });
}
```
The only change from the previous idea is the call to dispatch at the top level.  I'm pretty happy with this now.  I'll update gaearon/redux-thunk#32

**Comment by pburtchaell** [comment] 2015-11-23 14:40
Ok great. Please let us know if you have any other issues. Closing.

**Closed by pburtchaell** 2015-11-23 14:40 UTC
Labels: enhancement, question

**Comment by iarroyo5** [comment] 2018-02-07 12:56
@tesujimath we aware that when you are dispatching the action `updatePath('/')` your state hasn't achieved the `REQUEST_LOGIN_FULLIFED` state yet and you are updating the path without the state has been changed... I think you should concat the 
```
.then(json => {
   dispatch(updatePath('/'));
   resolve(json);
})
```

after the dispatch `REQUEST_LOGIN` has been finished or rejected, in this way:

export function requestLogin(email, password) {
  return (dispatch) => dispatch({
    type: REQUEST_LOGIN,
    payload: {
      promise: new Promise((resolve, reject) => {
        fetch(`${baseUrl}/api/v0/authenticate/password`, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: email,
            password: password
          })})
          .then(response => response.json())
          .then(json => {
            resolve(json);
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  })
  .then(() => dispatch(updatePath('/')))
  .catch(...);
}
