### ISSUE TITLE
Help With Error Handling Middleware

### ISSUE THREAD

**Issue by oviava** [pburtchaell/redux-promise-middleware#114] opened 2016-09-08 09:28 UTC
Hi,

This is not a bug but more of help, assistance request and it's related to the error middleware in your example.

In my codebase I'm using the error middleware to handle all promise rejections and forward them to an error handler. 

```js
const errorHandlingMiddleware = (errorHandler) => store => next => action => {
  const result = next(action);

  if (!isPromise(result)) {
    return action;
  }

  // if the action is marked by handled then I return the promise
  // additionally I would like to check if besides saying that is handled you provided a callback to the catch statement
  // to throw an invariant error
  if (action.meta && action.meta.isHandled) {
    return result;
  }

  return result.catch((error) => errorHandler(error, store));
};
```

What I'm trying to achieve .. without success so far is checking that besides specifying that your catch is handled by your action .. you actually provided a catch statement, and if not do an invariant violation.

EG:

```js

export const doStuff = (myParam) =>
  (dispatch) => dispatch({
    type: MY_ACTION,
    payload: MyService.doSomething(myParam),
    meta: {
      isHandled: true,
    },
  })
  .then(() => dispatch(mySideEffects));
  //.catch((err) => dispatch(myErrorHandler(err)));
// in this case I would want to throw an invariant in the middleware as meta.isHandled = true but you're not handling the errors
```

**Comment by pburtchaell** [comment] 2016-09-08 23:43
Hey @oviava!

> What I'm trying to achieve [is] checking that besides specifying that your catch is handled by 
your action, you actually provided a catch statement, and if not do an invariant violation.

**My understanding of the problem is**: when `action.meta.isHandled` has a erroneous value of `true`, throw an invariant in the middleware. In this case, `true` is an erroneous value when the error was _not_ handled. It should be `null` or `false`.

**Option A**: I can't solve this mentally—so off the top of my head I don't have a solution for you. Could you throw together a JS Bin example with your error middleware and the promise middleware? If I have some code to work with, I can try to find a solution for you. [This is a good JS Bin to use as a template](https://jsbin.com/bodopuqiyu/edit?html,js,output).

**Option B**: since the promise is uncaught, don't you already get an error in the console? What is the goal of throwing an invariant error?

**Comment by pburtchaell** [comment] 2016-09-14 12:34
Closing this issue. If you need further help, let me know.

**Closed by pburtchaell** 2016-09-14 12:34 UTC
Labels: help wanted
